import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Analytics } from "@vercel/analytics/next"
import { Inter } from 'next/font/google'
import { Providers } from './providers';
import ThemeToggle from '@/components/ThemeToggle';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Rohan Ghalib - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Analytics />
      <head>
      </head>
      <body className={inter.className}>
        <Providers>
          <ThemeToggle />
          {children}
        </Providers>
      </body>
    </html>
  );
}
